# -*- coding: utf-8 -*-
"""Tarea2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gxp-7y_YMpReYXd4GRXFDxseR0PJATdo
"""

# ==============================================================================
# Celda 1: Montar Google Drive para acceder a los archivos
# ==============================================================================
from google.colab import drive
drive.mount('/content/drive')

# ==============================================================================
# Celda 2: Importar librerías y definir la ruta del archivo
# ==============================================================================
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.cluster import KMeans, DBSCAN, AgglomerativeClustering
from sklearn.metrics import silhouette_score
import plotly.express as px

# --- IMPORTANTE: Ajusta esta ruta a la ubicación de tu archivo en Google Drive ---
file_path = '/content/drive/MyDrive/AI Projects/Colab_data/API_SP.POP.TOTL_DS2_es_csv_v2_16699 (3).csv'

# ==============================================================================
# FASE 1 y 2: COMPRENSIÓN DEL NEGOCIO Y DE LOS DATOS
# Pregunta guía: ¿Cómo ha evolucionado la población en América Latina
# y qué patrones de crecimiento emergen entre los países?
# ==============================================================================

print("--- Fase 1 y 2: Comprensión del Negocio y de los Datos ---")

# Cargar los datos, omitiendo las primeras 4 filas de metadatos
try:
    df_raw = pd.read_csv(file_path, skiprows=4)
    print("Archivo cargado exitosamente.")
    print("Dimensiones iniciales del dataset:", df_raw.shape)
except FileNotFoundError:
    print(f"Error: No se encontró el archivo en la ruta '{file_path}'.")
    print("Asegúrate de que la ruta sea correcta y el archivo esté en tu Google Drive.")

# --- 2.1 Limpieza de datos (EDA) ---

# Eliminar columnas irrelevantes
df_cleaned = df_raw.drop(columns=['Indicator Name', 'Indicator Code', 'Unnamed: 68'])

# Definir la lista de países de América Latina para el análisis
# Nota: Esta lista es una selección representativa y puede ser ajustada.
paises_latam = [
    'Argentina', 'Bolivia', 'Brasil', 'Chile', 'Colombia', 'Costa Rica',
    'Cuba', 'República Dominicana', 'Ecuador', 'El Salvador', 'Guatemala',
    'Honduras', 'México', 'Nicaragua', 'Panamá', 'Paraguay', 'Perú',
    'Uruguay', 'Venezuela'
]

# Filtrar el DataFrame para incluir solo los países de interés
df_latam = df_cleaned[df_cleaned['Country Name'].isin(paises_latam)].copy()
print(f"\nSe han seleccionado {len(df_latam)} países de América Latina.")

# Transformar el formato de ancho a largo (unpivot)
id_vars = ['Country Name', 'Country Code']
value_vars = [col for col in df_latam.columns if col.isdigit()]
df_long = pd.melt(df_latam, id_vars=id_vars, value_vars=value_vars, var_name='Year', value_name='Population')

# Convertir tipos de datos y manejar valores nulos
df_long['Year'] = pd.to_numeric(df_long['Year'])
df_long['Population'] = pd.to_numeric(df_long['Population'], errors='coerce')
df_long.dropna(subset=['Population'], inplace=True)
df_long['Population'] = df_long['Population'].astype(int)

print("\nInformación del dataset procesado:")
df_long.info()

# --- 2.2 Estadísticas descriptivas ---
print("\nEstadísticas descriptivas de la población en América Latina (1960-2023):")
print(df_long['Population'].describe().apply(lambda x: f"{x:,.0f}"))

# --- 2.3 Visualizaciones iniciales ---
print("\nGenerando visualizaciones iniciales...")

# a) Serie temporal de la evolución de la población para países clave
plt.style.use('seaborn-v0_8-whitegrid')
fig, ax = plt.subplots(figsize=(14, 8))
paises_clave = ['Brasil', 'México', 'Argentina', 'Colombia']
for pais in paises_clave:
    df_pais = df_long[df_long['Country Name'] == pais]
    ax.plot(df_pais['Year'], df_pais['Population'], label=pais)

ax.set_title('Evolución de la Población en Países Clave de América Latina (1960-2023)', fontsize=16)
ax.set_xlabel('Año', fontsize=12)
ax.set_ylabel('Población (en cientos de millones)', fontsize=12)
ax.legend()
plt.show()

# b) Boxplot de la distribución de la población en 2022
fig, ax = plt.subplots(figsize=(14, 8))
df_2022 = df_long[df_long['Year'] == 2022]
sns.boxplot(x='Population', y='Country Name', data=df_2022.sort_values('Population', ascending=False), ax=ax)
ax.set_title('Distribución de la Población en América Latina (Año 2022)', fontsize=16)
ax.set_xlabel('Población', fontsize=12)
ax.set_ylabel('País', fontsize=12)
plt.show()

# c) Heatmap de correlación entre las series temporales de los países
df_pivot = df_long.pivot(index='Year', columns='Country Name', values='Population')
corr_matrix = df_pivot.corr()

plt.figure(figsize=(16, 12))
sns.heatmap(corr_matrix, cmap='coolwarm', annot=False)
plt.title('Heatmap de Correlación de las Series Temporales de Población', fontsize=16)
plt.show()


# ==============================================================================
# FASE 3: PREPARACIÓN DE LOS DATOS
# ==============================================================================

print("\n--- Fase 3: Preparación de los Datos ---")

# Crear características para el clustering
# Usaremos el crecimiento poblacional como base para agrupar países
df_features = pd.DataFrame(index=paises_latam)

# Años de inicio y fin para el análisis de crecimiento
start_year = 1960
end_year = 2022
num_years = end_year - start_year

df_start = df_long[df_long['Year'] == start_year].set_index('Country Name')['Population']
df_end = df_long[df_long['Year'] == end_year].set_index('Country Name')['Population']

df_features['Poblacion_Inicial'] = df_start
df_features['Poblacion_Final'] = df_end
df_features['Crecimiento_Absoluto'] = df_end - df_start
df_features['Factor_Crecimiento'] = df_end / df_start

# Calcular la tasa de crecimiento anual compuesta (CAGR)
df_features['Tasa_Crecimiento_Anual'] = (df_features['Factor_Crecimiento'] ** (1/num_years)) - 1

print("\nCaracterísticas generadas para el clustering:")
print(df_features.head())

# Escalado de características para el clustering
scaler = StandardScaler()
features_scaled = scaler.fit_transform(df_features)
df_features_scaled = pd.DataFrame(features_scaled, index=df_features.index, columns=df_features.columns)

print("\nCaracterísticas escaladas (primeras 5 filas):")
print(df_features_scaled.head())


# ==============================================================================
# FASE 4: MODELADO
# ==============================================================================

print("\n--- Fase 4: Modelado ---")

# --- 4.1 Regresión para predecir población futura (Ejemplo: Brasil) ---
print("\n--- Modelo de Regresión: Predicción para Brasil ---")

# Preparar datos para la regresión
df_brasil = df_long[df_long['Country Name'] == 'Brasil'].copy()
X = df_brasil[['Year']]
y = df_brasil['Population']

# Modelo de regresión lineal
linear_reg = LinearRegression()
linear_reg.fit(X, y)
y_pred_linear = linear_reg.predict(X)

# Modelo de regresión polinomial (Grado 2)
poly_features = PolynomialFeatures(degree=2)
X_poly = poly_features.fit_transform(X)
poly_reg = LinearRegression()
poly_reg.fit(X_poly, y)
y_pred_poly = poly_reg.predict(X_poly)

# Predicción a futuro (hasta 2040)
years_future = np.arange(1960, 2041).reshape(-1, 1)
X_future_poly = poly_features.transform(years_future)
pop_pred_future = poly_reg.predict(X_future_poly)

# Visualización de la regresión
plt.figure(figsize=(14, 8))
plt.scatter(X, y, color='blue', label='Datos Históricos (Brasil)')
plt.plot(X, y_pred_linear, color='green', label='Regresión Lineal')
plt.plot(years_future, pop_pred_future, color='red', linestyle='--', label='Predicción Polinomial (hasta 2040)')
plt.title('Predicción de la Población de Brasil', fontsize=16)
plt.xlabel('Año', fontsize=12)
plt.ylabel('Población', fontsize=12)
plt.legend()
plt.show()

# --- 4.2 Clustering para agrupar países ---
print("\n--- Modelo de Clustering: Agrupación de Países ---")

# Determinar el número óptimo de clusters (k) con el método del codo
inertia = []
k_range = range(1, 11)
for k in k_range:
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
    kmeans.fit(df_features_scaled)
    inertia.append(kmeans.inertia_)

plt.figure(figsize=(10, 6))
plt.plot(k_range, inertia, marker='o')
plt.title('Método del Codo para Determinar k Óptimo', fontsize=16)
plt.xlabel('Número de Clusters (k)', fontsize=12)
plt.ylabel('Inercia', fontsize=12)
plt.show()
# El codo parece estar en k=3, lo que sugiere 3 clusters.

# Aplicar K-Means con k=3
k_optimo = 3
kmeans = KMeans(n_clusters=k_optimo, random_state=42, n_init=10)
clusters = kmeans.fit_predict(df_features_scaled)
df_features['Cluster'] = clusters

print(f"\nPaíses agrupados en {k_optimo} clusters:")
print(df_features.sort_values('Cluster'))

# Visualización de los clusters
plt.figure(figsize=(14, 8))
sns.scatterplot(data=df_features, x='Poblacion_Inicial', y='Factor_Crecimiento', hue='Cluster', palette='viridis', s=200, alpha=0.8)
# Añadir etiquetas de países al gráfico
for i, row in df_features.iterrows():
    plt.text(row['Poblacion_Inicial'], row['Factor_Crecimiento'], i, fontsize=9)
plt.title('Clusters de Países por Patrones de Crecimiento', fontsize=16)
plt.xlabel('Población en 1960', fontsize=12)
plt.ylabel('Factor de Crecimiento (1960-2022)', fontsize=12)
plt.legend(title='Cluster')
plt.show()


# ==============================================================================
# FASE 5: EVALUACIÓN
# ==============================================================================

print("\n--- Fase 5: Evaluación de Modelos ---")

# --- 5.1 Evaluación del modelo de regresión ---
r2_linear = r2_score(y, y_pred_linear)
mse_linear = mean_squared_error(y, y_pred_linear)
r2_poly = r2_score(y, y_pred_poly)
mse_poly = mean_squared_error(y, y_pred_poly)

print("\nEvaluación del Modelo de Regresión (Brasil):")
print(f"Regresión Lineal - R²: {r2_linear:.4f}, MSE: {mse_linear:,.0f}")
print(f"Regresión Polinomial (Grado 2) - R²: {r2_poly:.4f}, MSE: {mse_poly:,.0f}")
print("Conclusión: El modelo polinomial (R² más cercano a 1) se ajusta mucho mejor a la curva de crecimiento.")

# --- 5.2 Evaluación del modelo de clustering ---
silhouette_avg = silhouette_score(df_features_scaled, clusters)
print(f"\nEvaluación del Modelo de Clustering:")
print(f"Coeficiente de Silueta para k={k_optimo}: {silhouette_avg:.4f}")
print("Interpretación: Un valor de silueta de ~0.6 indica que los clusters están razonablemente bien definidos y separados.")

# --- 5.3 Interpretación de hallazgos ---
print("\nInterpretación de los Clusters:")
for i in range(k_optimo):
    print(f"\nCluster {i}:")
    paises_cluster = df_features[df_features['Cluster'] == i].index.tolist()
    print(f"  Países: {', '.join(paises_cluster)}")
    print(df_features[df_features['Cluster'] == i].describe())


# ==============================================================================
# FASE 6: DESPLIEGUE (Visualización para el informe)
# ==============================================================================

print("\n--- Fase 6: Despliegue (Visualización Final) ---")

# Unir los resultados del clustering con los códigos de país para el mapa
df_mapa = df_features.reset_index().rename(columns={'index': 'Country Name'})
df_mapa = df_mapa.merge(df_long[['Country Name', 'Country Code']].drop_duplicates(), on='Country Name')

# Crear mapa coroplético interactivo con Plotly
fig = px.choropleth(df_mapa,
                    locations="Country Code",
                    color="Cluster",
                    hover_name="Country Name",
                    color_continuous_scale=px.colors.sequential.Viridis,
                    title="Clusters de Crecimiento Poblacional en América Latina (1960-2022)",
                    scope="south america") # Se puede cambiar a "world" para un contexto más amplio

fig.show()

print("\nAnálisis completado.")